language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
    - pypy
    - pypy3

install:
    - pip install -r requirements-dev.txt
    - pip install coveralls

script:
    - flake8
    - make test

after_success:
    - coveralls
